### PR TITLE
Tests added

### PR DESCRIPTION
**Pull request by Wulfheart**
@Gummibeer recommended Snapshottests with this package: https://github.com/spatie/phpunit-snapshot-assertions

I added a basic test case. However, I still have to figure out how to test the color display but I'm tired right now. To be continued.

### CODE REVIEW

**Comment by saeidee** [comment]
Hi dear,

Nice package, thanks for your efforts, I think the snapshot testing here works as an Integration/Feature test, it still needs to have coverage for some other parts within the Unit Test(like as you mentioned colors or other logics within the command class), if you are ok I can create a PR for Unit Test and cover all of them.

**Comment by Wulfheart** [comment]
@saeidee That would be really nice. Thank you!

**Comment by Wulfheart** [comment]
@saeidee see #12 for thisn to be implemented.

**Comment by saeidee** [comment]
@Wulfheart dear, tests added here https://github.com/Wulfheart/pretty-routes/pull/19

**Pull request merged**
