### PR TITLE
Add only-path parameter

### PR DESCRIPTION
**Pull request by mattstauffer**
I don't know if this is the right name, but I've been talking for a while about wanting essentially a "grep" for the `route:list` command. I still want to add it one day to the core, but this seems an easy way to get it now!

image

### CODE REVIEW

**Comment by Wulfheart** [comment]
Nice addition.

**Comment by Gummibeer** [comment]
I assume that the "correct" name would be `--only=` as the inverse already exists `--exclude=` and everywhere in Laravel where we have an exclude method the inversion is "only".

**Comment by Wulfheart** [comment]
~Ok, I looked at it and thought it would be a nice addition but well, seems legit.~

Currently it is `--except-path=` in `route:list` and `route:pretty`.

**Comment by Gummibeer** [comment]
Oh yeah, sorry - my bad! 🙈🤯

**Pull request merged**
