### PR TITLE
added github actions to check phpcsfixer and phpunit tests

### PR DESCRIPTION
**Pull request by bhushan**
This PR will add 2 github actions

1. To check if the PR is following .php_cs.dist rules if not then it will apply those changes with commit message `Automatically applied php-cs-fixer changes`.
2. It checks if all tests are still passing when new PR is generated and also when pushed to master branch.

### CODE REVIEW

**Comment by Wulfheart** [comment]
Thanks for your PR. The changes in all other files are cosmetic?
How can I run the action locally? Via `act`?

**Comment by bhushan** [comment]
This will happen only once.. for the first time so it doesnt matter much.


but to avoid cosmetic changes. you can run phpcsfixer with configuration file you provided. (.php_cs.dist) and merge those changes. so in later PRs it will only apply changes on actual modified things by developer.

**Comment by Wulfheart** [comment]
Would you mind writing a Contributing.md for this?

**Comment by bhushan** [comment]
TBH I never wrote any `contributing.md` file. I have just used default by GitHub.

**Comment by Wulfheart** [comment]
Phew... I will have a look at it tomorrow or at saturday.

**Comment by Wulfheart** [comment]
Thanks for your contribution.

**Comment by Wulfheart** [comment]
Ok, I messed up. Would you mind making this PR against the dev branch? I messed a tiny little bit up and had to revert it. Shouldn't be doing things like that at 2am.

**Comment by bhushan** [comment]
Okay sending You PR again.. before EOD..

**Comment by bhushan** [comment]
What about Contributing.md ?

**Comment by Wulfheart** [comment]
> What about Contributing.md ?

I will write it myself. 



> Okay sending You PR again.. before EOD..

Thank you.

**Pull request merged**
